package com.interax.telephony.service.remote.interactivevoiceresponse;

import java.util.List;

import javax.ejb.Remote;

import com.interax.telephony.service.exception.interactivevoiceresponse.InteractiveVoiceResponseException;
import com.interax.telephony.service.interactivevoiceresponse.data.InteractiveVoiceResponseTransactionalRequest;
import com.interax.telephony.service.interactivevoiceresponse.data.InteractiveVoiceResponseTransactionalResponse;
import com.interax.telephony.util.InteraxTelephonyGenericEjb;


@Remote
public interface InteractiveVoiceResponseTransactionalController extends InteraxTelephonyGenericEjb
{
		/* Atomic Simple InteractiveVoiceResponse Management Methods */
		
		public InteractiveVoiceResponseTransactionalResponse loadInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> loadInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse addInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> addInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse updateInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> updateInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse removeInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> removeInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		
		/* Atomic Simple Did Management Methods */
		
		public InteractiveVoiceResponseTransactionalResponse loadDid(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> loadDids(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse addDid(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> addDids(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse updateDid(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> updateDids(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse removeDid(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> removeDids(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		
		/* Atomic Simple DidStep Management Methods */
		
		public InteractiveVoiceResponseTransactionalResponse loadDidStep(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> loadDidSteps(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse addDidStep(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> addDidSteps(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse updateDidStep(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> updateDidSteps(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse removeDidStep(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> removeDidSteps(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		
	
		
		/* Transaction Management Methods */
		
		public Long beginTransaction() throws Exception;
		public void commitTransaction(Long transactionId) throws Exception;
		public void rollbackTransaction(Long transactionId) throws Exception;
	
		
	/* Transactional Simple InteractiveVoiceResponse Management Methods */
		
		public InteractiveVoiceResponseTransactionalResponse loadInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> loadInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse addInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> addInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse updateInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> updateInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse removeInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> removeInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		
		
		/* Transactional Simple Did Management Methods */
		
		public InteractiveVoiceResponseTransactionalResponse loadDid(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> loadDids(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse addDid(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> addDids(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse updateDid(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> updateDids(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse removeDid(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> removeDids(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		
	/* Transactional Simple DidStep Management Methods */
		
		public InteractiveVoiceResponseTransactionalResponse loadDidStep(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> loadDidSteps(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse addDidStep(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> addDidSteps(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse updateDidStep(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> updateDidSteps(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse removeDidStep(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> removeDidSteps(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
	
		/* Atomic Complete Did Management Methods */
		
		public InteractiveVoiceResponseTransactionalResponse loadCompleteInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> loadCompleteInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse addCompleteInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> addCompleteInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse updateCompleteInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> updateCompleteInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse removeCompleteInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> removeCompleteInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		
		/* Transactional Complete InteractiveVoiceResponse Management Methods */
		
		public InteractiveVoiceResponseTransactionalResponse loadCompleteInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> loadCompleteInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse addCompleteInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> addCompleteInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse updateCompleteInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> updateCompleteInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse removeCompleteInteractiveVoiceResponse(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> removeCompleteInteractiveVoiceResponses(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
	
		
		
		/* Atomic Complete Did Management Methods */
		
		public InteractiveVoiceResponseTransactionalResponse loadCompleteDid(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> loadCompleteDids(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse addCompleteDid(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> addCompleteDids(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse updateCompleteDid(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> updateCompleteDids(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse removeCompleteDid(InteractiveVoiceResponseTransactionalRequest request) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> removeCompleteDids(List<InteractiveVoiceResponseTransactionalRequest> requests) throws InteractiveVoiceResponseException;
	
		/* Transactional Complete Did Management Methods */
		
		public InteractiveVoiceResponseTransactionalResponse loadCompleteDid(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> loadCompleteDids(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse addCompleteDid(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> addCompleteDids(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse updateCompleteDid(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> updateCompleteDids(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;
		public InteractiveVoiceResponseTransactionalResponse removeCompleteDid(InteractiveVoiceResponseTransactionalRequest request, Long transactionId) throws InteractiveVoiceResponseException;
		public List<InteractiveVoiceResponseTransactionalResponse> removeCompleteDids(List<InteractiveVoiceResponseTransactionalRequest> requests, Long transactionId) throws InteractiveVoiceResponseException;

}

