<?xml version="1.0"?>
<xsl:stylesheet version="1.0"
   xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
 <xsl:output method="xml"/>
 <xsl:variable name="smallcase" select="'abcdefghijklmnopqrstuvwxyz'" />
<xsl:variable name="uppercase" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'" />
 <xsl:template match="/">

&lt;!-- SIP Application Configuration File --&gt;
&lt;!-- Revision: <xsl:value-of select="phone_config/general/file/@version"/>  --&gt;
&lt;sip&gt; 
  &lt;voIpProt&gt; 
    &lt;local voIpProt.local.port=""/&gt;  
    &lt;server voIpProt.server.dhcp.available="0" voIpProt.server.dhcp.option="" voIpProt.server.dhcp.type="" voIpProt.server.dhcp.maxIpAddress=""/&gt;  
    &lt;SIP voIpProt.SIP.useRFC2543hold="0" voIpProt.SIP.sendCompactHdrs="0" voIpProt.SIP.WM50="0" voIpProt.SIP.ms-forking="" voIpProt.SIP.keepalive.sessionTimers="0" voIpProt.SIP.requestURI.E164.addGlobalPrefix="" voIpProt.SIP.allowTransferOnProceeding="1"&gt; 
      &lt;outboundProxy voIpProt.SIP.outboundProxy.address="<xsl:value-of select="phone_config/voip/sip/accounts/account/@server_ip"/>" voIpProt.SIP.outboundProxy.port="<xsl:value-of select="phone_config/voip/sip/accounts/account/@server_port"/>" voIpProt.SIP.outboundProxy.transport="DNSnaptr"/&gt;  
      &lt;alertInfo voIpProt.SIP.alertInfo.1.value="" voIpProt.SIP.alertInfo.1.class=""/&gt;  
      &lt;requestValidation voIpProt.SIP.requestValidation.1.request="" voIpProt.SIP.requestValidation.1.method="" voIpProt.SIP.requestValidation.1.request.1.event=""&gt; 
        &lt;digest voIpProt.SIP.requestValidation.digest.realm="PolycomSPIP"/&gt; 
      &lt;/requestValidation&gt;  
      &lt;specialEvent voIpProt.SIP.specialEvent.lineSeize.nonStandard="1" voIpProt.SIP.specialEvent.checkSync.alwaysReboot="1"/&gt;  
      &lt;conference voIpProt.SIP.conference.address="<xsl:value-of select="phone_config/voip/sip/accounts/account/@server_ip"/>"/&gt;  
      &lt;dialog voIpProt.SIP.dialog.useSDP="" voIpProt.SIP.dialog.usePvalue=""/&gt;  
      &lt;connectionReuse voIpProt.SIP.dialog.useAlias=""/&gt; 
    &lt;/SIP&gt; 
  &lt;/voIpProt&gt;  
  &lt;dialplan dialplan.impossibleMatchHandling="2" dialplan.removeEndOfDial="1"&gt; 
    &lt;digitmap dialplan.digitmap="[2-9]11|0T|100|101|011xxx.T|9011xxx.T|1[2-9]xxxxxxxxx|91[2-9]xxxxxxxxx|9[2-9]xxxxxx|*xx|[8]xxx|[2-7]xx" dialplan.digitmap.timeOut="3"/&gt;  
    &lt;routing&gt; 
      &lt;server dialplan.routing.server.1.address="<xsl:value-of select="phone_config/voip/sip/accounts/account/@server_ip"/>" 
	dialplan.routing.server.1.port="<xsl:value-of select="phone_config/voip/sip/accounts/account/@server_port"/>"/&gt;  
      &lt;emergency dialplan.routing.emergency.1.value="911" dialplan.routing.emergency.1.server.1="1"/&gt; 
    &lt;/routing&gt; 
  &lt;/dialplan&gt;  
  &lt;localization&gt; 
    &lt;multilingual&gt; 
      &lt;language lcl.ml.lang=""&gt;&lt;/language&gt; 
    &lt;/multilingual&gt;  
    &lt;datetime&gt; 
      &lt;time lcl.datetime.time.24HourClock="1"/&gt;  
      &lt;date lcl.datetime.date.format="D,Md" lcl.datetime.date.longFormat="1" lcl.datetime.date.dateTop="1"/&gt; 
    &lt;/datetime&gt; 
  &lt;/localization&gt;  
  &lt;user_preferences up.headsetMode="0" up.useDirectoryNames="0" up.oneTouchVoiceMail="0" up.welcomeSoundEnabled="1" up.welcomeSoundOnWarmBootEnabled="0" up.localClockEnabled="1"/&gt;  
  &lt;tones&gt; 
    &lt;DTMF tone.dtmf.level="-15" tone.dtmf.onTime="50" tone.dtmf.offTime="50" tone.dtmf.chassis.masking="0" tone.dtmf.stim.pac.offHookOnly="0" tone.dtmf.viaRtp="1" tone.dtmf.rfc2833Control="1" tone.dtmf.rfc2833Payload="101"/&gt; 
  &lt;/tones&gt;  
  &lt;sound_effects se.stutterOnVoiceMail="1" se.appLocalEnabled="1"&gt; 
    &lt;patterns&gt; 
      &lt;MISCELLANEOUS&gt; 
        &lt;MESSAGE_WAITING se.pat.misc.1.name="message waiting" se.pat.misc.1.inst.1.type="silence" se.pat.misc.1.inst.1.value="1" se.pat.misc.1.inst.2.type="silence" se.pat.misc.1.inst.2.value="2" se.pat.misc.1.inst.3.type="silence" se.pat.misc.1.inst.3.value="1"/&gt; 
      &lt;/MISCELLANEOUS&gt; 
    &lt;/patterns&gt;  
    &lt;ringType se.rt.enabled="1" se.rt.modification.enabled="1"&gt; 
      &lt;!-- Ring classes 3 and 4 are used by the Intercom feature --&gt;  
      &lt;RING_ANSWER se.rt.4.name="Ring Answer" se.rt.4.type="ring-answer" se.rt.4.timeout="2000" se.rt.4.ringer="2" se.rt.4.callWait="6" se.rt.4.mod="1"/&gt; 
    &lt;/ringType&gt; 
  &lt;/sound_effects&gt;  
  &lt;voice&gt; 
    &lt;codecs&gt; 
      &lt;preferences voice.codecPref.G711Mu="3" voice.codecPref.G711A="2" voice.codecPref.G729AB="1" voice.codecPref.IP_300.G711Mu="3" voice.codecPref.IP_300.G711A="2" voice.codecPref.IP_300.G729AB="1" voice.codecPref.IP_4000.G711Mu="3" voice.codecPref.IP_4000.G711A="2" voice.codecPref.IP_4000.G729AB="1" voice.codecPref.IP_650.G722="4" voice.codecPref.IP_650.G711Mu="2" voice.codecPref.IP_650.G711A="3" voice.codecPref.IP_650.G729AB="1"/&gt;  
      &lt;profiles voice.audioProfile.G711Mu.payloadSize="20" voice.audioProfile.G711Mu.jitterBufferMin="40" voice.audioProfile.G711Mu.jitterBufferShrink="500" voice.audioProfile.G711Mu.jitterBufferMax="160" voice.audioProfile.G711A.payloadSize="20" voice.audioProfile.G711A.jitterBufferMin="40" voice.audioProfile.G711A.jitterBufferShrink="500" voice.audioProfile.G711A.jitterBufferMax="160" voice.audioProfile.G729AB.payloadSize="20" voice.audioProfile.G729AB.jitterBufferMin="40" voice.audioProfile.G729AB.jitterBufferShrink="500" voice.audioProfile.G729AB.jitterBufferMax="160" voice.audioProfile.G722.payloadSize="20" voice.audioProfile.G722.jitterBufferMin="40" voice.audioProfile.G722.jitterBufferShrink="500" voice.audioProfile.G722.jitterBufferMax="160" voice.audioProfile.Lin16.payloadSize="10" voice.audioProfile.Lin16.jitterBufferMin="20" voice.audioProfile.Lin16.jitterBufferShrink="500" voice.audioProfile.Lin16.jitterBufferMax="100" voice.audioProfile.Lin16.frequency="16000" voice.audioProfile.Lin16.payloadType="117"/&gt; 
    &lt;/codecs&gt;  
    &lt;volume voice.volume.persist.handset="0" voice.volume.persist.headset="0" voice.volume.persist.handsfree="1"/&gt;  
    &lt;VAD voice.vadEnable="0" voice.vadThresh="15"/&gt; 
  &lt;/voice&gt;  
  &lt;QOS&gt; 
    &lt;Ethernet&gt; 
      &lt;RTP qos.ethernet.rtp.user_priority="5"/&gt;  
      &lt;CallControl qos.ethernet.callControl.user_priority="5"/&gt;  
      &lt;Other qos.ethernet.other.user_priority="2"/&gt; 
    &lt;/Ethernet&gt;  
    &lt;IP&gt; 
      &lt;RTP qos.ip.rtp.min_delay="1" qos.ip.rtp.max_throughput="1" qos.ip.rtp.max_reliability="0" qos.ip.rtp.min_cost="0" qos.ip.rtp.precedence="5"/&gt;  
      &lt;CallControl qos.ip.callControl.min_delay="1" qos.ip.callControl.max_throughput="0" qos.ip.callControl.max_reliability="0" qos.ip.callControl.min_cost="0" qos.ip.callControl.precedence="5"/&gt; 
    &lt;/IP&gt; 
  &lt;/QOS&gt;  
  &lt;TCP_IP&gt; 
    &lt;netMon tcpIpApp.netMon.enabled="1" tcpIpApp.netMon.period="30"/&gt;  
    &lt;SNTP tcpIpApp.sntp.resyncPeriod="86400" tcpIpApp.sntp.address="pool.ntp.org" tcpIpApp.sntp.address.overrideDHCP="1" tcpIpApp.sntp.gmtOffset="-18000" tcpIpApp.sntp.gmtOffset.overrideDHCP="0" tcpIpApp.sntp.daylightSavings.enable="1" tcpIpApp.sntp.daylightSavings.fixedDayEnable="0" tcpIpApp.sntp.daylightSavings.start.month="3" tcpIpApp.sntp.daylightSavings.start.date="2" tcpIpApp.sntp.daylightSavings.start.time="0" tcpIpApp.sntp.daylightSavings.start.dayOfWeek="3" tcpIpApp.sntp.daylightSavings.start.dayOfWeek.lastInMonth="0" tcpIpApp.sntp.daylightSavings.stop.month="11" tcpIpApp.sntp.daylightSavings.stop.date="1" tcpIpApp.sntp.daylightSavings.stop.time="2" tcpIpApp.sntp.daylightSavings.stop.dayOfWeek="3" tcpIpApp.sntp.daylightSavings.stop.dayOfWeek.lastInMonth="0"/&gt;  
    &lt;port&gt; 
      &lt;RTP tcpIpApp.port.rtp.filterByIp="1" tcpIpApp.port.rtp.filterByPort="0" tcpIpApp.port.rtp.forceSend="" tcpIpApp.port.rtp.mediaPortRangeStart=""/&gt; 
    &lt;/port&gt; 
  &lt;/TCP_IP&gt;  
  &lt;HTTPD httpd.enabled="1"&gt; 
    &lt;cfg httpd.cfg.enabled="1" httpd.cfg.port="80"/&gt; 
  &lt;/HTTPD&gt;  
  &lt;call call.rejectBusyOnDnd="1" call.enableOnNotRegistered="1" call.offeringTimeOut="60" call.ringBackTimeOut="60" call.lastCallReturnString="*69" call.callsPerLineKey="8" call.callWaiting.prompt="0"&gt; 
    &lt;shared call.shared.disableDivert="1" call.shared.seizeFailReorder="1" call.shared.oneTouchResume="0" call.shared.exposeAutoHolds=""/&gt;  
    &lt;hold&gt; 
      &lt;localReminder call.hold.localReminder.enabled="0" call.hold.localReminder.period="60" call.hold.localReminder.startDelay="90"/&gt; 
    &lt;/hold&gt; 
  &lt;/call&gt;  
  &lt;directory dir.local.volatile.2meg="0" dir.local.nonVolatile.maxSize.2meg="20" dir.local.volatile.4meg="0" dir.local.nonVolatile.maxSize.4meg="50" dir.local.volatile.maxSize="100"/&gt;  
  &lt;presence pres.reg=""/&gt;  
  &lt;keys key.scrolling.timeout="1"/&gt;  
  &lt;logging&gt; 
    &lt;level&gt; 
      &lt;change log.level.change.sip="4"/&gt; 
    &lt;/level&gt;  
    &lt;render log.render.level="1" log.render.type="2" log.render.realtime="1" log.render.stdout="1" log.render.file="1" log.render.file.size="16" log.render.file.upload.period="172800" log.render.file.upload.append="1" log.render.file.upload.append.sizeLimit="512" log.render.file.upload.append.limitMode="delete"/&gt; 
  &lt;/logging&gt;  
  &lt;security sec.tagSerialNo="0"&gt; 
    &lt;pwd&gt; 
      &lt;length sec.pwd.length.admin="1" sec.pwd.length.user="2"/&gt; 
    &lt;/pwd&gt;  
    &lt;SRTP sec.srtp.offer="" sec.srtp.require="" sec.srtp.lifetime=""/&gt; 
  &lt;/security&gt;  
  &lt;request&gt; 
    &lt;delay request.delay.type="call"/&gt; 
  &lt;/request&gt;  
  &lt;feature feature.1.name="presence" feature.1.enabled="0" feature.2.name="messaging" feature.2.enabled="0" feature.3.name="directory" feature.3.enabled="1" feature.4.name="calllist" feature.4.enabled="1" feature.5.name="ring-download" feature.5.enabled="1" feature.6.name="calllist-received" feature.6.enabled="1" feature.7.name="calllist-placed" feature.7.enabled="1" feature.8.name="calllist-missed" feature.8.enabled="1" feature.9.name="url-dialing" feature.9.enabled="1" feature.10.name="call-park" feature.10.enabled="0" feature.11.name="group-call-pickup" feature.11.enabled="0" feature.12.name="directed-call-pickup" feature.12.enabled="0" feature.13.name="last-call-return" feature.13.enabled="0" feature.14.name="acd-login-logout" feature.14.enabled="0" feature.15.name="acd-agent-availability" feature.15.enabled="0"/&gt;  
  &lt;microbrowser mb.proxy=""&gt; 
    &lt;main mb.main.home=""/&gt;  
    &lt;idleDisplay mb.idleDisplay.home="" mb.idleDisplay.refresh="0"/&gt;  
    &lt;limits mb.limits.nodes="" mb.limits.cache=""/&gt; 
  &lt;/microbrowser&gt; 
&lt;/sip&gt;

&lt;!-- Per-phone Configuration File --&gt;
&lt;!--  Revision: <xsl:value-of select="phone_config/general/file/@version"/>   --&gt;
&lt;POLYCOM<xsl:value-of select="translate(phone_config/general/file/@name, $uppercase, $smallcase)"/>&gt; 
  &lt;reg reg.1.displayName="<xsl:value-of select="phone_config/voip/sip/accounts/account/@username"/>" reg.1.address="203" reg.1.label="" reg.1.type="private" reg.1.thirdPartyName="" reg.1.auth.userId="<xsl:value-of select="phone_config/voip/sip/accounts/account/@username"/>" reg.1.auth.password="<xsl:value-of select="phone_config/voip/sip/accounts/account/@password"/>" reg.1.ringType="2" reg.1.lineKeys="" reg.1.callsPerLineKey="" reg.1.lcs="" reg.1.outboundProxy.address="" reg.1.outboundProxy.port="" reg.1.outboundProxy.transport="DNSnaptr" reg.1.server.1.address="scsha2.ca.nortel.com" reg.1.server.1.port="" reg.1.server.1.transport="DNSnaptr" reg.1.server.1.expires="" reg.1.server.1.expires.overlap="60" reg.1.server.1.register="" reg.1.server.1.retryTimeOut="" reg.1.server.1.retryMaxCount="" reg.1.server.1.expires.lineSeize="" reg.1.server.2.address="" reg.1.server.2.port="" reg.1.server.2.transport="DNSnaptr" reg.1.server.2.expires="" reg.1.server.2.expires.overlap="60" reg.1.server.2.register="" reg.1.server.2.retryTimeOut="" reg.1.server.2.retryMaxCount="" reg.1.server.2.expires.lineSeize="" reg.1.acd-login-logout="0" reg.1.acd-agent-available="0"/&gt;  
  &lt;call&gt; 
    &lt;donotdisturb call.donotdisturb.perReg="0"/&gt;  
    &lt;autoOffHook call.autoOffHook.1.enabled="0" call.autoOffHook.1.contact=""/&gt;  
    &lt;serverMissedCall call.serverMissedCall.1.enabled="0"/&gt; 
  &lt;/call&gt;  
  &lt;divert divert.1.contact="" divert.1.autoOnSpecificCaller="1" divert.1.sharedDisabled="1"&gt; 
    &lt;fwd divert.fwd.1.enabled="0"/&gt;  
    &lt;busy divert.busy.1.enabled="1" divert.busy.1.contact=""/&gt;  
    &lt;noanswer divert.noanswer.1.enabled="1" divert.noanswer.1.timeout="60" divert.noanswer.1.contact=""/&gt;  
    &lt;dnd divert.dnd.1.enabled="0" divert.dnd.1.contact=""/&gt; 
  &lt;/divert&gt;  
  &lt;dialplan dialplan.1.impossibleMatchHandling="0" dialplan.1.removeEndOfDial="1"&gt; 
    &lt;digitmap dialplan.1.digitmap="" dialplan.1.digitmap.timeOut=""/&gt;  
    &lt;routing&gt; 
      &lt;server dialplan.1.routing.server.1.address="" dialplan.1.routing.server.1.port=""/&gt;  
      &lt;emergency dialplan.1.routing.emergency.1.value="" dialplan.1.routing.emergency.1.server.1="1"/&gt; 
    &lt;/routing&gt; 
  &lt;/dialplan&gt;  
  &lt;msg msg.bypassInstantMessage="0"&gt; 
    &lt;mwi msg.mwi.1.subscribe="" msg.mwi.1.callBackMode="" msg.mwi.1.callBack=""/&gt; 
  &lt;/msg&gt;  
  &lt;nat nat.ip="" nat.signalPort="" nat.mediaPortStart=""/&gt;  
  &lt;attendant attendant.uri="" attendant.reg=""/&gt;  
  &lt;roaming_buddies roaming_buddies.reg=""/&gt;  
  &lt;roaming_privacy roaming_privacy.reg=""/&gt; 
&lt;/<xsl:value-of select="translate(phone_config/general/file/@name, $uppercase, $smallcase)"/>POLYCOM&gt;
</xsl:template>
</xsl:stylesheet>
